# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-02 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.CharField(max_length=200),
        ),
    ]
